
const D=window.PETER_NOTES;
const app=document.getElementById('app');
const search=document.getElementById('search');

const systems=[
 "CARDIOLOGY","GASTROINTESTINAL TRACT","RESPIRATORY SYSTEM","RENAL SYSTEM",
 "ENDOCRINE SYSTEM","HAEMATOLOGY","DERMATOLOGY","General Practice"
];

function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function paras(){return D.content.filter(x=>x.type==="paragraph").map(x=>x.text)}
function topicCards(filter=""){
 let arr=D.topics.filter(t=>!filter || t.toLowerCase().includes(filter.toLowerCase()));
 return arr.slice(0,180).map(t=>`<div class="card" onclick="openTopic(${JSON.stringify(t)})"><h3>${esc(t)}</h3><p>From your notes</p></div>`).join("");
}
function home(){
 app.innerHTML=`<div class="page">
 <div class="hero"><div class="crumb">YOUR PERSONAL MEDICAL KNOWLEDGE BASE</div>
 <h1>Study from your notes.</h1><p>This site reorganises <b>your own notes</b> into a searchable, interactive study system. The source material is not supplemented with external medical information.</p>
 <div class="toolbar"><button class="btn primary" onclick="browse()">Browse topics</button><button class="btn" onclick="questions()">Practice questions</button></div></div>
 <div class="section"><div class="section-head">Systems</div><div class="section-body"><div class="grid">${systems.map(s=>`<div class="card" onclick="browse(${JSON.stringify(s)})"><h3>${esc(s)}</h3><p>Topics from your notes</p></div>`).join("")}</div></div></div>
 <div class="section"><div class="section-head">Source rule</div><div class="section-body warning">Everything currently displayed comes from <b>${esc(D.sourceFile)}</b>. No external medical content has been added.</div></div>
 </div>`;
}
function browse(filter=""){
 app.innerHTML=`<div class="page"><div class="crumb">BROWSE</div><h1>Topics</h1><p class="muted">Structured from headings and content in your notes.</p><div class="grid">${topicCards(filter)}</div></div>`;
}
function rapid(){
 const ps=paras().filter(x=>x.length>20).slice(0,80);
 app.innerHTML=`<div class="page"><div class="crumb">RAPID REVIEW</div><h1>Rapid review</h1><p class="muted">A compact stream of statements taken directly from your notes.</p><div class="section"><div class="section-body">${ps.map(x=>`<div class="note-line">• ${esc(x)}</div>`).join("")}</div></div></div>`;
}
function openTopic(title){
 const all=paras(), idx=all.findIndex(x=>x.toLowerCase()===title.toLowerCase());
 let start=Math.max(0,idx), end=Math.min(all.length,idx+70);
 // Include subsequent source paragraphs until a clear next heading-like block.
 let chosen=all.slice(start,end);
 app.innerHTML=`<div class="page"><div class="crumb">YOUR NOTES / TOPIC</div><h1 class="topic-title">${esc(title)}</h1>
 <div class="toolbar"><button class="btn" onclick="browse()">← Back to topics</button><button class="btn primary" onclick="questions(${JSON.stringify(title)})">Test this topic</button></div>
 <div class="section"><div class="section-head">Source content</div><div class="section-body note">${chosen.map(x=>`<div class="note-line">${esc(x)}</div>`).join("")}</div></div>
 <div class="warning">This page is a reorganisation of your notes only. No outside information has been added.</div></div>`;
}
function searchAll(q){
 const terms=q.toLowerCase().trim().split(/\s+/).filter(Boolean);
 if(!terms.length){home();return}
 const results=[];
 D.content.forEach((it,i)=>{
   const text=it.type==="paragraph"?it.text:it.rows.flat().join(" | ");
   const low=text.toLowerCase();
   if(terms.every(t=>low.includes(t))) results.push({i,text});
 });
 app.innerHTML=`<div class="page"><div class="crumb">SEARCH</div><h1>Search results</h1><p class="muted">${results.length} result(s) from your notes.</p>
 <div class="section">${results.slice(0,100).map(r=>`<div class="search-result" onclick="jump(${r.i})"><b>${esc(r.text.slice(0,140))}${r.text.length>140?"…":""}</b><div class="match">Source note</div></div>`).join("") || '<div class="section-body muted">No matching note found.</div>'}</div></div>`;
}
function jump(i){
 const item=D.content[i]; if(!item)return;
 app.innerHTML=`<div class="page"><div class="crumb">SEARCH RESULT</div><div class="section"><div class="section-head">Your note</div><div class="section-body note">${esc(item.type==="paragraph"?item.text:item.rows.map(r=>r.join(" | ")).join("\n"))}</div></div><button class="btn" onclick="searchAll(search.value)">← Back to results</button></div>`;
}
function questions(topic=""){
 const source=paras().filter(x=>x.length>30);
 let pool=source;
 if(topic){
   const i=source.findIndex(x=>x.toLowerCase().includes(topic.toLowerCase()));
   if(i>=0) pool=source.slice(i,Math.min(source.length,i+35));
 }
 // Questions are generated by selecting source statements and turning them into simple recall prompts.
 const base=pool.filter(x=>x.length>35).slice(0,30);
 if(!base.length){app.innerHTML='<div class="page"><h1>Practice questions</h1><p class="muted">There is not enough source text in this topic to construct a question without adding information.</p></div>';return}
 const statement=base[Math.floor(Math.random()*base.length)];
 const words=statement.replace(/[^\w’'-]+/g," ").split(/\s+/).filter(w=>w.length>5);
 const answer=words[0]||statement.split(/\s+/)[0];
 app.innerHTML=`<div class="page"><div class="crumb">PRACTICE</div><div class="question"><h1>Practice question</h1><div class="warning">Question content is generated only from your notes. This prototype uses simple recall questions; it does not invent missing medical facts.</div>
 <div class="section"><div class="section-body"><h2>Which statement is contained in your notes?</h2>
 <button class="option" onclick="showAnswer()">${esc(statement)}</button>
 <button class="option" onclick="showAnswer()">A different statement not selected from the source</button>
 <button class="option" onclick="showAnswer()">Another statement not selected from the source</button>
 <button class="option" onclick="showAnswer()">Another statement not selected from the source</button>
 <button class="option" onclick="showAnswer()">Another statement not selected from the source</button>
 <div id="answer"></div></div></div></div></div>`;
 window.showAnswer=()=>document.getElementById("answer").innerHTML=`<div class="answer"><b>Source answer:</b><br>${esc(statement)}</div>`;
}
document.querySelectorAll(".nav").forEach(b=>b.addEventListener("click",()=>{
 document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));b.classList.add("active");
 const v=b.dataset.view;if(v==="home")home();if(v==="browse")browse();if(v==="rapid")rapid();if(v==="questions")questions();
}));
search.addEventListener("keydown",e=>{if(e.key==="Enter")searchAll(search.value)});
window.home=home;window.browse=browse;window.rapid=rapid;window.openTopic=openTopic;window.questions=questions;window.searchAll=searchAll;window.jump=jump;
home();
